### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by tbsmn** [LytixDev/tomatoshell#1]
Hi I get the following Error when I start die script.

```
./tomatoshell: line 76: "1641469099" + 900: syntax error: operand expected (error token is ""1641469099" + 900")
```

Any Ideas what is causing this?

**Comment by LytixDev** [comment]
Changing line 76 from 
`start=$(("$(date +%s)" + $1)); `
to
`start=$(($(date +%s) + $1)); `
may solve the issue, but I don't understand why it would be an issue. Works fine for me.

What happens if you type:
`echo $((" "1" + 1 "))`
in your shell? It should return 2.

**Comment by tbsmn** [comment]
Guess that's because I use zsh. If i try with bash the error is gone.

But instead i get this:

```
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
```

**Comment by LytixDev** [comment]
The +%s flag on date might be specific for GNU's date and not be a part of POSIX date. If you're not using GNU coreutils then that might explain it.

**Comment by tbsmn** [comment]
OK sounds legit. Thanks for checking it.

**Comment by LytixDev** [comment]
Hmm I thought adding the `#!/bin/bash` shebang would start the script with bash. I changed the shebang to `#!/usr/bin/env bash` which now hopefully should start it with bash.
