### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by dpakkia** [LytixDev/tomatoshell#18]
Hello, I used the tool for a while successfully, now I get this:
`/usr/local/bin/tomatoshell: row 134: [: -eq: unary operator expected`
`/usr/local/bin/tomatoshell: row 142: [: -ne: unary operator expected`
`/usr/local/bin/tomatoshell: row 150: [: -ne: unary operator expected`
`Break finished`
`Press 's' to stop alarm/usr/local/bin/tomatoshell: row 86: [: -eq: unary operator expected`

I use zsh, so I tried switching back to bash, but the results are the same. What should I do?

**Comment by dviewy** [comment]
I have the same issue...

**Comment by LytixDev** [comment]
Hi. Are you on the latest version? I am unable to replicate the issue. I am using bash. What arguments are you starting the program with?

**Comment by LytixDev** [comment]
This pr: https://github.com/LytixDev/tomatoshell/pull/19, may solve the issue.

**Comment by LytixDev** [comment]
Are you able to try this branch? https://github.com/LytixDev/tomatoshell/pull/19. It may fix the issue. I am unsure as I can't recreate it.

**Comment by dviewy** [comment]
@LytixDev now i am getting this error :( I did not pass any parameters when starting

`Time left of session 1/3:
/usr/local/bin/tomatoshell: line 137: 1681032652 + : syntax error: operand expected (error token is "+ ")

exiting
➜  tomatoshell git:(fix/globbing)`

**Comment by salihgerdan** [comment]
I had the same issue, turns out the cause is not having `bc` installed. `bc` needs to be added to the AUR package dependencies.

**Comment by LytixDev** [comment]
Thanks @salihgerdan. bc was added to the PKBUILD some time ago, but the package was never updated to the AUR. I will do this asap.

**Comment by LytixDev** [comment]
version has now been updated on the AUR
